### ISSUE TITLE
Error during running the visualizer

### ISSUE THREAD

**Issue by JiajieLi7012** [hwanhuh/2D-GS-Viser-Viewer#12]
Hi,

Thanks for building such a great tool. But I got the following error when I ran it in Colab and even if I manually created the file it still doesn't work. Any help would be appreciated.

```
Traceback (most recent call last):
  File "/content/2d-gaussian-splatting/viewer.py", line 566, in <module>
    viewer.start()
  File "/content/2d-gaussian-splatting/viewer.py", line 241, in start
    self.edit_panel = EditPanel(server, self, edit_tab)
  File "/content/2d-gaussian-splatting/internal/viewer/ui/edit_panel.py", line 34, in __init__
    self.export_mesh_block()
  File "/content/2d-gaussian-splatting/internal/viewer/ui/edit_panel.py", line 331, in export_mesh_block
    with open(self._mesh_export_log_dir, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/content/2d-gaussian-splatting/temp/mesh_log.txt'
```

**Comment by hwanhuh** [comment]
I think that the file writing in Colab can be the problem. 
In the mesh export process, I saved the printed message to the log txt file and sent it to the new modal in Viser. 
You can ignore the log_thread and start_logging part in the viewer.py likes, 

```python 
def _(event: viser.GuiEvent) -> None:
            with self.server.atomic():
                with event.client.add_gui_modal("[Mesh Export]") as modal:
                    self.export_mesh_text = event.client.add_gui_markdown(self._default_export_log)
                    close_button = event.client.add_gui_button("Close", visible=False)
                    @close_button.on_click
                    def _(_) -> None:
                        modal.close()

            # Update the GUI first before starting the thread
            def update_gui_and_start_export():
                def export() -> None:
                    ex_args, model_params, export_pipe_params = MeshExporter.parse_args_mesh(self.viewer.model_paths, 
                                                                                            self.viewer.source_path, 
                                                                                            self.viewer.args, 
                                                                                            unbounded = self.unbounded.value, 
                                                                                            mesh_res = self.mesh_res.value, 
                                                                                            num_cluster = self.num_cluster.value)
                    mesh_exporter = MeshExporter(ex_args, self.viewer.gaussian_model, self.viewer.iteration, model_params, export_pipe_params)
                    # mesh_exporter.start_logging(self._mesh_export_log_dir)
                    self.mesh_path = mesh_exporter.export_mesh()
                    # mesh_exporter.stop_logging()

                def update_log() -> None:
                    while export_thread.is_alive():
                        self.export_mesh_text.content = self._default_export_log + read_last_lines(self._mesh_export_log_dir, 15)
                        time.sleep(0.1)
                    
                export_thread = threading.Thread(target=export)
                # log_thread = threading.Thread(target=update_log)
                export_thread.start()
                # log_thread.start()
                export_thread.join()
                # log_thread.join()
                self.export_mesh_text.content = f'Done! \n Your Mesh is saved at: {self.mesh_path}'
                close_button.visible = True

            # Call the function to update the GUI and start the export process
            update_gui_and_start_export()
```

**Comment by hwanhuh** [comment]
updated
